[package]
default-run = "profilectl"
name        = "profilectl"
description = "Profile-based dotfiles and developer machine automation."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
keywords.workspace     = true
categories.workspace   = true

[lints]
workspace = true

[dependencies]
profilectl-cli = { workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
tracing                = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[[test]]
name = "integration"
path = "tests/it/integration.rs"
