xflags::xflags! {
    src "./src/flags.rs"

    /// Dev automation for the profilectl workspace.
    cmd xtask {
        /// Format check + cargo check + clippy -D warnings.
        cmd check {}
        /// Build all workspace crates.
        cmd build {}
        /// Full test suite via cargo nextest.
        cmd test {}
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Check(Check),
    Build(Build),
    Test(Test),
}

#[derive(Debug)]
pub struct Check {}

#[derive(Debug)]
pub struct Build {}

#[derive(Debug)]
pub struct Test {}

#[expect(dead_code)]
impl Xtask {
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
